furu-app/force-app/main/default/objects/Contract/fields/April__c.field-meta.xml
<CustomField>
    <fullName>April__c</fullName>
    <label>April</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/August__c.field-meta.xml
<CustomField>
    <fullName>August__c</fullName>
    <label>August</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/ContractNumber__c.field-meta.xml
<CustomField>
    <fullName>ContractNumber__c</fullName>
    <label>Mã HĐ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/December__c.field-meta.xml
<CustomField>
    <fullName>December__c</fullName>
    <label>December</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/ExRateM10__c.field-meta.xml
<CustomField>
    <fullName>ExRateM10__c</fullName>
    <defaultValue>208</defaultValue>
    <label>ExRateM10</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/ExRateM11__c.field-meta.xml
<CustomField>
    <fullName>ExRateM11__c</fullName>
    <defaultValue>208</defaultValue>
    <label>ExRateM11</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/ExRateM12__c.field-meta.xml
<CustomField>
    <fullName>ExRateM12__c</fullName>
    <defaultValue>208</defaultValue>
    <label>ExRateM12</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/ExRateM1__c.field-meta.xml
<CustomField>
    <fullName>ExRateM1__c</fullName>
    <defaultValue>208</defaultValue>
    <label>ExRateM1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/ExRateM2__c.field-meta.xml
<CustomField>
    <fullName>ExRateM2__c</fullName>
    <defaultValue>208</defaultValue>
    <label>ExRateM2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/ExRateM3__c.field-meta.xml
<CustomField>
    <fullName>ExRateM3__c</fullName>
    <defaultValue>208</defaultValue>
    <label>ExRateM3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/ExRateM4__c.field-meta.xml
<CustomField>
    <fullName>ExRateM4__c</fullName>
    <defaultValue>208</defaultValue>
    <label>ExRateM4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/ExRateM5__c.field-meta.xml
<CustomField>
    <fullName>ExRateM5__c</fullName>
    <defaultValue>208</defaultValue>
    <label>ExRateM5</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/ExRateM6__c.field-meta.xml
<CustomField>
    <fullName>ExRateM6__c</fullName>
    <defaultValue>208</defaultValue>
    <label>ExRateM6</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/ExRateM7__c.field-meta.xml
<CustomField>
    <fullName>ExRateM7__c</fullName>
    <defaultValue>208</defaultValue>
    <label>ExRateM7</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/ExRateM8__c.field-meta.xml
<CustomField>
    <fullName>ExRateM8__c</fullName>
    <defaultValue>208</defaultValue>
    <label>ExRateM8</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/ExRateM9__c.field-meta.xml
<CustomField>
    <fullName>ExRateM9__c</fullName>
    <defaultValue>208</defaultValue>
    <label>ExRateM9</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/February__c.field-meta.xml
<CustomField>
    <fullName>February__c</fullName>
    <label>February</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/January__c.field-meta.xml
<CustomField>
    <fullName>January__c</fullName>
    <label>January</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/July__c.field-meta.xml
<CustomField>
    <fullName>July__c</fullName>
    <label>July</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/June__c.field-meta.xml
<CustomField>
    <fullName>June__c</fullName>
    <label>June</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/March__c.field-meta.xml
<CustomField>
    <fullName>March__c</fullName>
    <label>March</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/May__c.field-meta.xml
<CustomField>
    <fullName>May__c</fullName>
    <label>May</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/November__c.field-meta.xml
<CustomField>
    <fullName>November__c</fullName>
    <label>November</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/October__c.field-meta.xml
<CustomField>
    <fullName>October__c</fullName>
    <label>October</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

furu-app/force-app/main/default/objects/Contract/fields/September__c.field-meta.xml
<CustomField>
    <fullName>September__c</fullName>
    <label>September</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

furu-app/force-app/main/default/classes/FURU_ContractManagermentController.cls
public with sharing class FURU_ContractManagermentController {
    //private static final Decimal EX_RATE = Decimal.valueOf(System.Label.furu_ContractDetailFormExchangeRate);
    @AuraEnabled
    public static List<Resouce> getResources(){
        List<Resouce> resources = new List<Resouce>();

        for (Account acc : getAllAccounts()) {
            String recordType = acc.recordType != null ? acc.recordType.DeveloperName : null;
            resources.add(new Resouce(
                acc.Id,
                acc.Name,
                recordType
            ));
        }
        return resources;
    }

    @AuraEnabled
    public static List<Event> getEvents(Integer year){
        List<Event> events = new List<Event>();
        for (Contract contract : getAllContract(year)) {
            Map <String, String> mapMonthApiName = getMapMonthAndExrateApiName();
            Integer monthIndex = 1;
            for (String monthApiName: mapMonthApiName.keySet()){
                Decimal monthValue = (Decimal)contract.get(monthApiName);
                Decimal exrateValue = (Decimal)contract.get(mapMonthApiName.get(monthApiName));
                if (monthValue != null){
                    /*Integer month = mapMonthApiName.get(monthApiName); */
                   	Integer month = monthIndex;
                    Integer endDay = daysInMonth(month, year);
                    String startDate = formatDate(Date.newInstance(year, month, 1));
                    String endDate = formatDate(Date.newInstance(year, month, endDay));
                    String income = convertValue(monthValue*exrateValue);
                    events.add(new Event(contract.Id,contract.AccountId, contract.ContractNumber__c, startDate, endDate, monthValue, income));
                }
                monthIndex ++ ;
            }
        }
        return events;
    }

    public class Resouce {
        @AuraEnabled public string id           {get; set;}
        @AuraEnabled public string title        {get; set;}
        @AuraEnabled public string recordType   {get ;set;}
        public Resouce(String resourceId, String resourceTitle, String recordType) {
            this.id = resourceId;
            this.title = resourceTitle;
            this.recordType = recordType;
        }
    }

    public class Event {
        @AuraEnabled public String  id              {get; set;}
        @AuraEnabled public String  resourceId      {get; set;}
        @AuraEnabled public String  title           {get; set;}
        @AuraEnabled public String  start           {get; set;}
        @AuraEnabled public String  finish          {get; set;}
        @AuraEnabled public Decimal value           {get; set;}
        @AuraEnabled public String  income          {get; set;}
        
        public Event(String id ,String resourceId, String title, String startDate, String endDate, Decimal value, String income){
            this.id = id;
            this.resourceId = resourceId;
            this.title = title;
            this.start = formatDate(Date.valueOf(startDate));
            this.finish = formatDate(Date.valueOf(endDate));
            this.value = value;
            this.income = income;
        }
    }

    private static List<Account> getAllAccounts() {
        return [SELECT Id, Name, RecordType.DeveloperName FROM Account];
    }

    public static List<Contract> getAllContract(Integer year) {
        List<String> listFields = new List<String>(getMapMonthAndExrateApiName().keySet());
        listFields.addAll(getMapMonthAndExrateApiName().values());
        listFields.addAll(new List<String>{'Id','AccountId','ContractNumber__c','StartDate','EndDate'});
        String listFieldsString = String.join(listFields, ',');
        String condition = ' (CALENDAR_YEAR(StartDate) =: year OR CALENDAR_YEAR(EndDate) =: year)';
        String queryString = String.format('SELECT {0} FROM Contract WHERE {1}', new String[]{listFieldsString, condition});
        System.debug(Database.query(queryString));
        return Database.query(queryString);
    }
    private static Map<String, String> getMapMonthAndExrateApiName(){
        return new Map<String, String>{'January__c' => 'ExRateM1__c',
                                        'February__c' => 'ExRateM2__c',
                                        'March__c' => 'ExRateM3__c',
                                        'April__c' => 'ExRateM4__c',
                                        'May__c' => 'ExRateM5__c',
                                        'June__c' => 'ExRateM6__c', 
                                        'July__c' => 'ExRateM7__c',
                                        'August__c' => 'ExRateM8__c',
                                        'September__c' =>'ExRateM9__c',
                                        'October__c' => 'ExRateM10__c',
                                        'November__c' => 'ExRateM11__c',
                                        'December__c' => 'ExRateM12__c'
                                        };
    }
    private static String formatDate(Date d) {
        return DateTime.newInstance(
            d.year(), d.month(), d.day()
        ).format('yyyy-MM-dd');
    }
    private static Integer daysInMonth(Integer month, Integer year){
        return 32 - Date.newInstance(year, month, 32).day();
    }
    private static String convertValue (Decimal d) {
        // prepend currency symbol
        Return d.format() + ' VND';
    }
}